# Generated by Django 2.2.7 on 2019-12-17 18:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('body_slot', models.CharField(blank=True, choices=[('Head', 'Head'), ('Face', 'Face'), ('Torso', 'Torso'), ('Back', 'Back'), ('Throat', 'Throat'), ('Arm', 'Arm'), ('Hand', 'Hand'), ('Ring', 'Ring'), ('Body', 'Body'), ('Waist', 'Waist'), ('Legs', 'Legs'), ('Main Hand', 'Main Hand'), ('Off Hand', 'Off Hand')], max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.Equipment')),
                ('armor_bonus', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('bonus_type', models.CharField(choices=[('alch', 'Alchemical'), ('armor', 'Armor'), ('circ', 'Circumstance'), ('comp', 'Competence'), ('def', 'Deflection'), ('div', 'Divine'), ('dodge', 'Dodge'), ('enh', 'Enhancement'), ('epic', 'Epic'), ('exal', 'Exalted'), ('ins', 'Insight'), ('luck', 'Luck'), ('morale', 'Morale'), ('nat', 'Natural Armor'), ('prof', 'Profane'), ('racial', 'Racial'), ('resist', 'Resistance'), ('sacred', 'Sacred'), ('shield', 'Shield'), ('sice', 'Size'), ('untyped', 'Untyped')], default='armor', max_length=10)),
                ('armor_check_penalty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('movement_penalty', models.IntegerField(choices=[(0, 'None'), (5, '5 ft'), (10, '10 ft')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('spell_failure_chance', models.IntegerField(choices=[(0, 'None'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (50, '50%')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Armor',
            },
            bases=('equipment.equipment',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.Equipment')),
                ('damage_dice', models.CharField(max_length=5)),
                ('two_handed', models.BooleanField(default=False)),
                ('crit_range', models.CharField(default='20/x2', max_length=10)),
                ('range_increment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            bases=('equipment.equipment',),
        ),
    ]
