ALIGNMENT_CHOICES = (
    ('LG', 'Lawful Good'),
    ('NG', 'Neutral Good'),
    ('CG', 'Chaotic Good'),
    ('LN', 'Lawful Neutral'),
    ('N', 'True Neutral'),
    ('CN', 'Chaotic Neutral'),
    ('LE', 'Lawful Evil'),
    ('NE', 'Neutral Evil'),
    ('CE', 'Chaotic Evil'),
)

SEX_CHOICES = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Other', 'Other'),
)

ZODIAC_CHOICES = (
    ('Aries', 'Aries'),
    ('Leo', 'Leo'),
    ('Cancer', 'Cancer'),
    ('Pisces', 'Pisces'),
    ('Scorpio', 'Scorpio'),
    ('Taurus', 'Taurus'),
    ('Sagittarius', 'Sagittarius'),
    ('Gemini', 'Gemini'),
    ('Virgo', 'Virgo'),
    ('Libra', 'Libra'),
    ('Caricorn', 'Capricorn'),
    ('Aquarius', 'Aquarius'),
)

ATTRIBUTE_CHOICES = (
    ('strength', 'Strength'),
    ('dexterity', 'Dexterity'),
    ('constitution', 'Constituion'),
    ('intelligence', 'Intelligence'),
    ('wisdom', 'Wisdom'),
    ('charisma', 'Charisma')
)

DEFAULT_SKILLS = {
    'Acrobatics': 0,
    'Artifice': 0,
    'Autohypnosis': 0,
    'Bluff': 0,
    'Climb': 0,
    'Concentration': 0,
    'Craft': 0,
    'Decipher Script': 0,
    'Diplomacy': 0,
    'Disguise': 0,
    'Escape Artist': 0,
    'Forgery': 0,
    'Handle Animal': 0,
    'Heal': 0,
    'Intimidate': 0,
    'Knowledge: Arcana': 0,
    'Knowledge: Architecture and Engineering': 0,
    'Knowledge: Dungeoneering': 0,
    'Knowledge: History': 0,
    'Knowledge: Local': 0,
    'Knowledge: Military and Tactics': 0,
    'Knowledge: Nature': 0,
    'Knowledge: Nobility and Royalty': 0,
    'Knowledge: Psionics': 0,
    'Knowledge: Religion': 0,
    'Knowledge: The Planes': 0,
    'Magecraft': 0,
    'Perform': 0,
    'Ride': 0,
    'Sense Motive': 0,
    'Sleight of Hand': 0,
    'Speak Language': 0,
    'Stealth': 0,
    'Survival': 0,
    'Swim': 0,
    'Use Rope': 0,
}
