# Generated by Django 2.2.7 on 2019-12-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='bonus_tyoe',
            new_name='bonus_type',
        ),
    ]
