# Generated by Django 3.0.1 on 2019-12-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcane',
            name='class_spell_list',
        ),
        migrations.RemoveField(
            model_name='chant',
            name='class_spell_list',
        ),
        migrations.RemoveField(
            model_name='epic',
            name='class_spell_list',
        ),
        migrations.RemoveField(
            model_name='power',
            name='class_spell_list',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='class_spell_list',
        ),
        migrations.RemoveField(
            model_name='song',
            name='class_spell_list',
        ),
    ]
