# Generated by Django 3.0.1 on 2019-12-20 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20191218_1007'),
        ('spells', '0002_auto_20191220_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcane',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
        migrations.AddField(
            model_name='chant',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
        migrations.AddField(
            model_name='epic',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
        migrations.AddField(
            model_name='power',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
        migrations.AddField(
            model_name='song',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
    ]
