# Generated by Django 2.2.7 on 2019-12-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_auto_20191217_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
