# Generated by Django 3.0.1 on 2019-12-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0003_auto_20191220_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcane',
            name='descriptors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chant',
            name='descriptors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='epic',
            name='descriptors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='descriptors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='descriptors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='descriptors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
