# Generated by Django 3.0.1 on 2019-12-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0006_auto_20191220_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcane',
            name='casting_time',
            field=models.CharField(default='Standard Action', max_length=50),
        ),
        migrations.AddField(
            model_name='chant',
            name='casting_time',
            field=models.CharField(default='Standard Action', max_length=50),
        ),
        migrations.AddField(
            model_name='epic',
            name='casting_time',
            field=models.CharField(default='Standard Action', max_length=50),
        ),
        migrations.AddField(
            model_name='power',
            name='casting_time',
            field=models.CharField(default='Standard Action', max_length=50),
        ),
        migrations.AddField(
            model_name='prayer',
            name='casting_time',
            field=models.CharField(default='Standard Action', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='casting_time',
            field=models.CharField(default='Standard Action', max_length=50),
        ),
    ]
