# Generated by Django 3.0.1 on 2019-12-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0007_auto_20191220_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcane',
            name='spell_range',
            field=models.CharField(default='Short', max_length=50),
        ),
        migrations.AddField(
            model_name='chant',
            name='spell_range',
            field=models.CharField(default='Short', max_length=50),
        ),
        migrations.AddField(
            model_name='epic',
            name='spell_range',
            field=models.CharField(default='Short', max_length=50),
        ),
        migrations.AddField(
            model_name='power',
            name='spell_range',
            field=models.CharField(default='Short', max_length=50),
        ),
        migrations.AddField(
            model_name='prayer',
            name='spell_range',
            field=models.CharField(default='Short', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='spell_range',
            field=models.CharField(default='Short', max_length=50),
        ),
    ]
