# Generated by Django 3.0.1 on 2019-12-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0008_auto_20191220_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcane',
            name='duration',
            field=models.CharField(default='Instantaneous', max_length=50),
        ),
        migrations.AddField(
            model_name='chant',
            name='duration',
            field=models.CharField(default='Instantaneous', max_length=50),
        ),
        migrations.AddField(
            model_name='epic',
            name='duration',
            field=models.CharField(default='Instantaneous', max_length=50),
        ),
        migrations.AddField(
            model_name='power',
            name='duration',
            field=models.CharField(default='Instantaneous', max_length=50),
        ),
        migrations.AddField(
            model_name='prayer',
            name='duration',
            field=models.CharField(default='Instantaneous', max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(default='Instantaneous', max_length=50),
        ),
    ]
