# Generated by Django 3.0.1 on 2019-12-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0010_auto_20191220_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arcane',
            name='save',
        ),
        migrations.RemoveField(
            model_name='chant',
            name='save',
        ),
        migrations.RemoveField(
            model_name='epic',
            name='save',
        ),
        migrations.RemoveField(
            model_name='power',
            name='save',
        ),
        migrations.RemoveField(
            model_name='prayer',
            name='save',
        ),
        migrations.RemoveField(
            model_name='song',
            name='save',
        ),
        migrations.AddField(
            model_name='arcane',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chant',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='power',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
