# Generated by Django 3.0.1 on 2019-12-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20191218_1007'),
        ('spells', '0013_auto_20191220_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcane',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arcane',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
        migrations.AddField(
            model_name='arcane',
            name='components',
            field=models.CharField(default='V, S, M', max_length=20),
        ),
        migrations.AddField(
            model_name='arcane',
            name='spell_resistance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='arcane',
            name='spell_save',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chant',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chant',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
        migrations.AddField(
            model_name='chant',
            name='components',
            field=models.CharField(default='V, S, M', max_length=20),
        ),
        migrations.AddField(
            model_name='chant',
            name='spell_resistance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chant',
            name='spell_save',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
        migrations.AddField(
            model_name='epic',
            name='components',
            field=models.CharField(default='V, S, M', max_length=20),
        ),
        migrations.AddField(
            model_name='epic',
            name='spell_resistance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='epic',
            name='spell_save',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='power',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='power',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
        migrations.AddField(
            model_name='power',
            name='components',
            field=models.CharField(default='V, S, M', max_length=20),
        ),
        migrations.AddField(
            model_name='power',
            name='spell_resistance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='power',
            name='spell_save',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
        migrations.AddField(
            model_name='prayer',
            name='components',
            field=models.CharField(default='V, S, M', max_length=20),
        ),
        migrations.AddField(
            model_name='prayer',
            name='spell_resistance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='spell_save',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='class_spell_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass'),
        ),
        migrations.AddField(
            model_name='song',
            name='components',
            field=models.CharField(default='V, S, M', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='spell_resistance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='spell_save',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
