# Generated by Django 3.0.1 on 2019-12-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0014_auto_20191220_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invocation',
            old_name='save',
            new_name='invocation_save',
        ),
        migrations.RenameField(
            model_name='mystery',
            old_name='save',
            new_name='mystery_save',
        ),
        migrations.RemoveField(
            model_name='mystery',
            name='path_level',
        ),
        migrations.AddField(
            model_name='invocation',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
