# Generated by Django 2.0.7 on 2019-11-30 18:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(choices=[('strength', 'Strength'), ('dexterity', 'Dexterity'), ('constitution', 'Constituion'), ('intelligence', 'Intelligence'), ('wisdom', 'Wisdom'), ('charisma', 'Charisma')], default='strength', max_length=11)),
                ('bonus', models.IntegerField()),
                ('bonus_type', models.CharField(choices=[('alch', 'Alchemical'), ('armor', 'Armor'), ('circ', 'Circumstance'), ('comp', 'Competence'), ('def', 'Deflection'), ('div', 'Divine'), ('dodge', 'Dodge'), ('enh', 'Enhancement'), ('epic', 'Epic'), ('exal', 'Exalted'), ('ins', 'Insight'), ('luck', 'Luck'), ('morale', 'Morale'), ('nat', 'Natural Armor'), ('prof', 'Profane'), ('racial', 'Racial'), ('resist', 'Resistance'), ('sacred', 'Sacred'), ('shield', 'Shield'), ('sice', 'Size'), ('untyped', 'Untyped')], default='untyped', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('hit_die', models.IntegerField(choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12')], default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_Name', models.CharField(max_length=50)),
                ('hair_Color', models.CharField(blank=True, max_length=16, null=True)),
                ('eye_Color', models.CharField(blank=True, max_length=16, null=True)),
                ('height', models.CharField(blank=True, help_text='Height typically in feet', max_length=6, null=True)),
                ('weight', models.IntegerField(blank=True, default=100, help_text='Weight in lbs', validators=[django.core.validators.MinValueValidator(1)])),
                ('age', models.IntegerField(blank=True, default=25, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_HP', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_HP', models.IntegerField(default=1)),
                ('base_Strength', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('base_Dexterity', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('base_Constitution', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('base_Intelligence', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('base_Wisdom', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('base_Charisma', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('personal_Traits', models.TextField(blank=True, default='')),
                ('ideals', models.TextField(blank=True, default='')),
                ('flaws', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('alignment', models.IntegerField(choices=[(0, 'Lawful Good'), (1, 'Neutral Good'), (2, 'Chaotic Good'), (3, 'Lawful Neutral'), (4, 'True Neutral'), (5, 'Chaotic Neutral'), (6, 'Lawful Evil'), (7, 'Neutral Evil'), (8, 'Chaotic Evil')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('zodiac_Sign', models.IntegerField(blank=True, choices=[(0, 'Aries'), (1, 'Leo'), (2, 'Cancer'), (3, 'Pisces'), (4, 'Scorpio'), (5, 'Taurus'), (6, 'Sagittarius'), (7, 'Gemini'), (8, 'Virgo'), (9, 'Libra'), (10, 'Capricorn'), (11, 'Aquarius')], default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('attribute_bonuses', models.ManyToManyField(related_name='_feat_attribute_bonuses_+', to='characters.AttributeBonus')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racial_name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('special_abilities', models.TextField()),
                ('non_playable', models.BooleanField(default=False)),
                ('attribute_bonuses', models.ManyToManyField(related_name='_race_attribute_bonuses_+', to='characters.AttributeBonus')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='SkillBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField()),
                ('bonus_type', models.CharField(choices=[('alch', 'Alchemical'), ('armor', 'Armor'), ('circ', 'Circumstance'), ('comp', 'Competence'), ('def', 'Deflection'), ('div', 'Divine'), ('dodge', 'Dodge'), ('enh', 'Enhancement'), ('epic', 'Epic'), ('exal', 'Exalted'), ('ins', 'Insight'), ('luck', 'Luck'), ('morale', 'Morale'), ('nat', 'Natural Armor'), ('prof', 'Profane'), ('racial', 'Racial'), ('resist', 'Resistance'), ('sacred', 'Sacred'), ('shield', 'Shield'), ('sice', 'Size'), ('untyped', 'Untyped')], default='untyped', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subrace_name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('special_abilities', models.TextField()),
                ('attribute_bonus', models.ManyToManyField(related_name='_subrace_attribute_bonus_+', to='characters.AttributeBonus')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Race')),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.Equipment')),
                ('armor_bonus', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('bonus_type', models.CharField(choices=[('alch', 'Alchemical'), ('armor', 'Armor'), ('circ', 'Circumstance'), ('comp', 'Competence'), ('def', 'Deflection'), ('div', 'Divine'), ('dodge', 'Dodge'), ('enh', 'Enhancement'), ('epic', 'Epic'), ('exal', 'Exalted'), ('ins', 'Insight'), ('luck', 'Luck'), ('morale', 'Morale'), ('nat', 'Natural Armor'), ('prof', 'Profane'), ('racial', 'Racial'), ('resist', 'Resistance'), ('sacred', 'Sacred'), ('shield', 'Shield'), ('sice', 'Size'), ('untyped', 'Untyped')], default='armor', max_length=10)),
                ('armor_check_penalty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('movement_penalty', models.IntegerField(choices=[(0, 'None'), (5, '5 ft'), (10, '10 ft')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('spell_failure_chance', models.IntegerField(choices=[(0, 'None'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%'), (30, '30%'), (35, '35%'), (40, '40%'), (50, '50%')], default=0)),
            ],
            bases=('characters.equipment',),
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('baseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.BaseClass')),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            bases=('characters.baseclass',),
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('skill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.Skill')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            bases=('characters.skill',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.Equipment')),
                ('damage_dice', models.CharField(max_length=5)),
                ('two_handed', models.BooleanField(default=False)),
                ('crit_range', models.CharField(default='20/x2', max_length=10)),
                ('range_increment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            bases=('characters.equipment',),
        ),
        migrations.AddField(
            model_name='skillbonus',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='synergies',
            field=models.ManyToManyField(blank=True, related_name='_skill_synergies_+', to='characters.Skill'),
        ),
        migrations.AddField(
            model_name='feat',
            name='skill_bonuses',
            field=models.ManyToManyField(related_name='_feat_skill_bonuses_+', to='characters.SkillBonus'),
        ),
        migrations.AddField(
            model_name='character',
            name='feats',
            field=models.ManyToManyField(blank=True, related_name='_character_feats_+', to='characters.Feat'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.Race'),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='class_skills',
            field=models.ManyToManyField(related_name='_baseclass_class_skills_+', to='characters.Skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_classes',
            field=models.ManyToManyField(related_name='character', to='characters.CharacterClass'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='_character_skills_+', to='characters.CharacterSkill'),
        ),
    ]
