# Generated by Django 2.2.7 on 2019-12-11 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillbonus',
            name='skill',
        ),
        migrations.AlterModelOptions(
            name='armor',
            options={'verbose_name_plural': 'Armor'},
        ),
        migrations.AlterModelOptions(
            name='baseclass',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='characterclass',
            options={'verbose_name_plural': 'Character Classes'},
        ),
        migrations.AlterModelOptions(
            name='classability',
            options={'verbose_name_plural': 'Class Abilities'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='subrace',
            options={'verbose_name_plural': 'Sub-Races'},
        ),
        migrations.AddField(
            model_name='baseclass',
            name='fort',
            field=models.CharField(choices=[('Good', 'Good'), ('Poor', 'Poor')], default='Poor', max_length=4),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='reflex',
            field=models.CharField(choices=[('Good', 'Good'), ('Poor', 'Poor')], default='Poor', max_length=4),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='will',
            field=models.CharField(choices=[('Good', 'Good'), ('Poor', 'Poor')], default='Poor', max_length=4),
        ),
        migrations.AddField(
            model_name='equipment',
            name='body_slot',
            field=models.CharField(blank=True, choices=[('Head', 'Head'), ('Face', 'Face'), ('Torso', 'Torso'), ('Back', 'Back'), ('Throat', 'Throat'), ('Arm', 'Arm'), ('Hand', 'Hand'), ('Ring', 'Ring'), ('Body', 'Body'), ('Waist', 'Waist'), ('Legs', 'Legs'), ('Main Hand', 'Main Hand'), ('Off Hand', 'Off Hand')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RemoveField(
            model_name='feat',
            name='attribute_bonuses',
        ),
        migrations.AddField(
            model_name='feat',
            name='attribute_bonuses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='feat',
            name='skill_bonuses',
        ),
        migrations.AddField(
            model_name='feat',
            name='skill_bonuses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='race',
            name='attribute_bonuses',
        ),
        migrations.AddField(
            model_name='race',
            name='attribute_bonuses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='playable',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='race',
            name='skill_bonuses',
        ),
        migrations.AddField(
            model_name='race',
            name='skill_bonuses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='synergies',
        ),
        migrations.AddField(
            model_name='skill',
            name='synergies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='attribute_bonuses',
        ),
        migrations.AddField(
            model_name='subrace',
            name='attribute_bonuses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='skill_bonuses',
        ),
        migrations.AddField(
            model_name='subrace',
            name='skill_bonuses',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AttributeBonus',
        ),
        migrations.DeleteModel(
            name='SkillBonus',
        ),
    ]
