# Generated by Django 3.0.2 on 2020-01-05 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseclass',
            name='spells_known',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='spells_per_level',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='baseclass',
            name='class_abilities',
        ),
        migrations.AddField(
            model_name='baseclass',
            name='class_abilities',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.RemoveField(
            model_name='baseclass',
            name='class_skills',
        ),
        migrations.AddField(
            model_name='baseclass',
            name='class_skills',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='ClassAbility',
        ),
    ]
