# Generated by Django 2.2.7 on 2019-12-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseclass',
            name='class_abilities',
            field=models.ManyToManyField(blank=True, to='characters.ClassAbility'),
        ),
        migrations.AlterField(
            model_name='baseclass',
            name='class_skills',
            field=models.ManyToManyField(blank=True, related_name='_baseclass_class_skills_+', to='characters.Skill'),
        ),
    ]
