# Generated by Django 2.2.7 on 2019-11-30 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(choices=[('LG', 'Lawful Good'), ('NG', 'Neutral Good'), ('CG', 'Chaotic Good'), ('LN', 'Lawful Neutral'), ('N', 'True Neutral'), ('CN', 'Chaotic Neutral'), ('LE', 'Lawful Evil'), ('NE', 'Neutral Evil'), ('CE', 'Chaotic Evil')], default='LG', max_length=2),
        ),
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.IntegerField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='zodiac_Sign',
            field=models.CharField(choices=[('Aries', 'Aries'), ('Leo', 'Leo'), ('Cancer', 'Cancer'), ('Pisces', 'Pisces'), ('Scorpio', 'Scorpio'), ('Taurus', 'Taurus'), ('Sagittarius', 'Sagittarius'), ('Gemini', 'Gemini'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Caricorn', 'Capricorn'), ('Aquarius', 'Aquarius')], default=0, max_length=20),
        ),
    ]
