# Generated by Django 2.2.7 on 2019-11-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20191130_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='skill_bonuses',
            field=models.ManyToManyField(related_name='_race_skill_bonuses_+', to='characters.SkillBonus'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='skill_bonuses',
            field=models.ManyToManyField(related_name='_subrace_skill_bonuses_+', to='characters.SkillBonus'),
        ),
    ]
