# Generated by Django 2.2.7 on 2019-11-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20191130_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_Classes',
            field=models.ManyToManyField(related_name='character_class', to='characters.CharacterClass'),
        ),
        migrations.AlterField(
            model_name='subrace',
            name='subrace_name',
            field=models.CharField(max_length=30),
        ),
    ]
