# Generated by Django 2.1.3 on 2018-12-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20181201_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='Character_Name',
            new_name='character_name',
        ),
    ]
