# Generated by Django 2.2.7 on 2019-12-15 03:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20191211_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('level_equivalent', models.CharField(blank=True, max_length=100, null=True)),
                ('invocation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('save', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='MartialManeuver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('maneuver_type', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mystery_rank', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('path_level', models.IntegerField()),
                ('mystery_range', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('save', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PactInvocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('descriptors', models.CharField(max_length=50)),
                ('casting_time', models.CharField(max_length=50)),
                ('spell_range', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('save', models.CharField(blank=True, max_length=50, null=True)),
                ('bonus_tyoe', models.CharField(max_length=50)),
                ('damage_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('class_spell_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.BaseClass')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vestige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ruling_star', models.CharField(max_length=50)),
                ('summoning_req', models.CharField(max_length=3)),
                ('binding_DC', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('strength', models.CharField(max_length=50)),
                ('tenacity', models.CharField(max_length=50)),
                ('force', models.CharField(max_length=50)),
                ('intellect', models.CharField(max_length=50)),
                ('will', models.CharField(max_length=50)),
                ('cunning', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chant',
            fields=[
                ('spell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.Spell')),
                ('sphere', models.CharField(max_length=20)),
            ],
            bases=('characters.spell',),
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('spell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.Spell')),
                ('discipline', models.CharField(max_length=20)),
            ],
            bases=('characters.spell',),
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('spell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.Spell')),
                ('domain', models.CharField(max_length=20)),
            ],
            bases=('characters.spell',),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('spell_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.Spell')),
                ('chord', models.CharField(max_length=20)),
            ],
            bases=('characters.spell',),
        ),
        migrations.CreateModel(
            name='DisciplinePower',
            fields=[
                ('power_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='characters.Power')),
                ('discipline_list', models.CharField(max_length=15)),
            ],
            bases=('characters.power',),
        ),
    ]
