# Generated by Django 2.2.7 on 2019-12-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_feat_feat_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feat',
            options={'ordering': ['feat_classification', 'feat_name']},
        ),
    ]
