# Generated by Django 3.0.2 on 2020-01-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_auto_20200105_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
