# Generated by Django 3.0.2 on 2020-01-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20200105_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseclass',
            name='base_attack_bonus',
            field=models.CharField(choices=[('Poor', 'Poor'), ('Moderate', 'Moderate'), ('Good', 'Good')], default='Poor', max_length=1000),
        ),
    ]
