# Generated by Django 2.2.7 on 2019-12-09 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20191209_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='baseclass',
            name='skill_points',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='baseclass',
            name='class_abilities',
            field=models.ManyToManyField(to='characters.ClassAbility'),
        ),
    ]
