# Generated by Django 2.0.7 on 2018-12-02 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20181201_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='eye_Color',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_Color',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='height_Units',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
