# Generated by Django 3.0.2 on 2020-01-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_baseclass_base_attack_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='base_Charisma',
            new_name='base_charisma',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='base_Constitution',
            new_name='base_constitution',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='base_Dexterity',
            new_name='base_dexterity',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='base_Intelligence',
            new_name='base_intelligence',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='base_Strength',
            new_name='base_strength',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='base_Wisdom',
            new_name='base_wisdom',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_Classes',
            new_name='character_classes',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_Name',
            new_name='character_name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='current_HP',
            new_name='current_hp',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='eye_Color',
            new_name='eye_color',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='hair_Color',
            new_name='hair_color',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='max_HP',
            new_name='max_hp',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='personal_Traits',
            new_name='personal_traits',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='zodiac_Sign',
            new_name='zodiac_sign',
        ),
    ]
