# Generated by Django 3.0.2 on 2020-01-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20200109_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='subrace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.Subrace'),
        ),
    ]
