# Generated by Django 2.0.7 on 2018-12-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20181201_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
