# Generated by Django 3.0.2 on 2020-01-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_character_subrace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.CharField(default={'Acrobatics': 0, 'Artifice': 0, 'Autohypnosis': 0, 'Bluff': 0, 'Climb': 0, 'Concentration': 0, 'Craft': 0, 'Decipher Script': 0, 'Diplomacy': 0, 'Disguise': 0, 'Escape Artist': 0, 'Forgery': 0, 'Handle Animal': 0, 'Heal': 0, 'Intimidate': 0, 'Knowledge: Arcana': 0, 'Knowledge: Architecture and Engineering': 0, 'Knowledge: Dungeoneering': 0, 'Knowledge: History': 0, 'Knowledge: Local': 0, 'Knowledge: Military and Tactics': 0, 'Knowledge: Nature': 0, 'Knowledge: Nobility and Royalty': 0, 'Knowledge: Psionics': 0, 'Knowledge: Religion': 0, 'Knowledge: The Planes': 0, 'Magecraft': 0, 'Perform': 0, 'Ride': 0, 'Sense Motive': 0, 'Sleight of Hand': 0, 'Speak Language': 0, 'Stealth': 0, 'Survival': 0, 'Swim': 0, 'Use Rope': 0}, max_length=1000),
        ),
        migrations.DeleteModel(
            name='CharacterSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
