# Generated by Django 2.0.7 on 2018-12-02 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_auto_20181201_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='height_Units',
        ),
    ]
