# Generated by Django 2.0.7 on 2018-12-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_remove_character_height_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='eye_Color',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_Color',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
