# Generated by Django 3.0.2 on 2020-01-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20200110_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='size',
            field=models.CharField(default='Medium', max_length=25),
        ),
        migrations.AddField(
            model_name='race',
            name='speed',
            field=models.CharField(default='30 ft', max_length=10),
        ),
    ]
