# Generated by Django 3.0.2 on 2020-01-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_auto_20200110_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='classification',
            field=models.CharField(default='Humanoid', max_length=100),
        ),
    ]
