# Generated by Django 3.0.2 on 2020-01-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_race_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='favored_class',
            field=models.CharField(default='Any', max_length=50),
        ),
    ]
