# Generated by Django 3.0.2 on 2020-01-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_race_favored_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='automatic_languages',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
