# Generated by Django 3.0.2 on 2020-01-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_race_automatic_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='bonus_languages',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
