# Generated by Django 3.0.2 on 2020-01-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_race_bonus_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='skill_bonuses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
