# Generated by Django 3.0.2 on 2020-01-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_auto_20200115_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='feats',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subrace',
            name='automatic_languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subrace',
            name='bonus_languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='subrace',
            name='favored_class',
            field=models.CharField(default='Any', max_length=50),
        ),
        migrations.AddField(
            model_name='subrace',
            name='feats',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseclass',
            name='spells_per_level',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills',
            field=models.CharField(default={'Acrobatics': {'armor_check': True, 'attribute': 'Dexterity', 'ranks': 0, 'total': 0, 'trained': True}, 'Artifice': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Autohypnosis': {'armor_check': False, 'attribute': 'Wisdom', 'ranks': 0, 'total': 0, 'trained': True}, 'Bluff': {'armor_check': False, 'attribute': 'Charisma', 'ranks': 0, 'total': 0, 'trained': False}, 'Climb': {'armor_check': True, 'attribute': 'Strength', 'ranks': 0, 'total': 0, 'trained': False}, 'Concentration': {'armor_check': False, 'attribute': 'Constitution', 'ranks': 0, 'total': 0, 'trained': False}, 'Craft': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': False}, 'Decipher Script': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Diplomacy': {'armor_check': False, 'attribute': 'Charisma', 'ranks': 0, 'total': 0, 'trained': False}, 'Disguise': {'armor_check': False, 'attribute': 'Charisma', 'ranks': 0, 'total': 0, 'trained': False}, 'Escape Artist': {'armor_check': True, 'attribute': 'Dexterity', 'ranks': 0, 'total': 0, 'trained': False}, 'Forgery': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': False}, 'Handle Animal': {'armor_check': False, 'attribute': 'Wisdom', 'ranks': 0, 'total': 0, 'trained': True}, 'Heal': {'armor_check': False, 'attribute': 'Wisdom', 'ranks': 0, 'total': 0, 'trained': False}, 'Intimidate': {'armor_check': False, 'attribute': 'Charisma', 'ranks': 0, 'total': 0, 'trained': False}, 'Knowledge: Arcana': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Knowledge: Architecture and Engineering': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Knowledge: Dungeoneering': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Knowledge: History': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Knowledge: Local': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Knowledge: Military and Tactics': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Knowledge: Nature': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Knowledge: Nobility and Royalty': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Knowledge: Psionics': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Knowledge: Religion': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Knowledge: The Planes': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Magecraft': {'armor_check': False, 'attribute': 'Intelligence', 'ranks': 0, 'total': 0, 'trained': True}, 'Perception': {'armor_check': False, 'attribute': 'Wisdom', 'ranks': 0, 'total': 0, 'trained': False}, 'Perform': {'armor_check': False, 'attribute': 'Charisma', 'ranks': 0, 'total': 0, 'trained': False}, 'Ride': {'armor_check': False, 'attribute': 'Dexterity', 'ranks': 0, 'total': 0, 'trained': False}, 'Sense Motive': {'armor_check': False, 'attribute': 'Wisdom', 'ranks': 0, 'total': 0, 'trained': False}, 'Sleight of Hand': {'armor_check': True, 'attribute': 'Dexterity', 'ranks': 0, 'total': 0, 'trained': True}, 'Speak Language': {'languages': [], 'ranks': 0}, 'Stealth': {'armor_check': True, 'attribute': 'Dexterity', 'ranks': 0, 'total': 0, 'trained': False}, 'Survival': {'armor_check': False, 'attribute': 'Wisdom', 'ranks': 0, 'total': 0, 'trained': False}, 'Swim': {'armor_check': True, 'attribute': 'Strength', 'ranks': 0, 'total': 0, 'trained': False}, 'Use Rope': {'armor_check': False, 'attribute': 'Dexterity', 'ranks': 0, 'total': 0, 'trained': False}}, max_length=1000),
        ),
        migrations.AlterField(
            model_name='race',
            name='attribute_bonuses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subrace',
            name='attribute_bonuses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subrace',
            name='skill_bonuses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
